### Create Paper
POST http://localhost:5158/Paper
Content-Type: application/json

{
  "name": "Sample Paper",
  "discontinued": false,
  "stock": 100,
  "price": 9.99
}

> {%
    client.test("Request is successful", function() {
        client.assert(response.status === 201, "Expected status code to be 201");
    });
%}

### Update Paper status
PUT http://localhost:5158/Paper/2/status?discontinued=true
Content-Type: application/json

> {%
    client.test("Request is successful", function() {
        client.assert(response.status === 200, "Expected status code to be 200");
    });
%}

### Add Stock to Paper
PUT http://localhost:5158/Paper/2/addstock?stock=10
Content-Type: application/json

> {%
    client.test("Request is successful", function() {
        client.assert(response.status === 200, "Expected status code to be 200");
    });
%}